// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IcoCommon.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CampaignSettingsCreateOrUpdateRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CampaignSettingsCreateOrUpdateRequest class.
        /// </summary>
        public CampaignSettingsCreateOrUpdateRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CampaignSettingsCreateOrUpdateRequest class.
        /// </summary>
        public CampaignSettingsCreateOrUpdateRequest(CampaignSettingsModel campaignSettings = default(CampaignSettingsModel), string username = default(string))
        {
            CampaignSettings = campaignSettings;
            Username = username;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "campaignSettings")]
        public CampaignSettingsModel CampaignSettings { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (CampaignSettings != null)
            {
                CampaignSettings.Validate();
            }
        }
    }
}
