// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IcoCommon.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CampaignSettingsModel
    {
        /// <summary>
        /// Initializes a new instance of the CampaignSettingsModel class.
        /// </summary>
        public CampaignSettingsModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CampaignSettingsModel class.
        /// </summary>
        public CampaignSettingsModel(string transactionQueueSasUrl = default(string), SmtpSettings smtp = default(SmtpSettings))
        {
            TransactionQueueSasUrl = transactionQueueSasUrl;
            Smtp = smtp;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transactionQueueSasUrl")]
        public string TransactionQueueSasUrl { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "smtp")]
        public SmtpSettings Smtp { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (Smtp != null)
            {
                Smtp.Validate();
            }
        }
    }
}
