// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IcoCommon.Client.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for CurrencyType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CurrencyType
    {
        [EnumMember(Value = "BTC")]
        BTC,
        [EnumMember(Value = "ETH")]
        ETH,
        [EnumMember(Value = "USD")]
        USD
    }
    internal static class CurrencyTypeEnumExtension
    {
        internal static string ToSerializedValue(this CurrencyType? value)
        {
            return value == null ? null : ((CurrencyType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this CurrencyType value)
        {
            switch( value )
            {
                case CurrencyType.BTC:
                    return "BTC";
                case CurrencyType.ETH:
                    return "ETH";
                case CurrencyType.USD:
                    return "USD";
            }
            return null;
        }

        internal static CurrencyType? ParseCurrencyType(this string value)
        {
            switch( value )
            {
                case "BTC":
                    return CurrencyType.BTC;
                case "ETH":
                    return CurrencyType.ETH;
                case "USD":
                    return CurrencyType.USD;
            }
            return null;
        }
    }
}
