// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IcoCommon.Client.Models
{
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;
    using System.Runtime;
    using System.Runtime.Serialization;

    /// <summary>
    /// Defines values for CurrencyType.
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum CurrencyType
    {
        [EnumMember(Value = "btc")]
        Btc,
        [EnumMember(Value = "eth")]
        Eth,
        [EnumMember(Value = "usd")]
        Usd
    }
    internal static class CurrencyTypeEnumExtension
    {
        internal static string ToSerializedValue(this CurrencyType? value)
        {
            return value == null ? null : ((CurrencyType)value).ToSerializedValue();
        }

        internal static string ToSerializedValue(this CurrencyType value)
        {
            switch( value )
            {
                case CurrencyType.Btc:
                    return "btc";
                case CurrencyType.Eth:
                    return "eth";
                case CurrencyType.Usd:
                    return "usd";
            }
            return null;
        }

        internal static CurrencyType? ParseCurrencyType(this string value)
        {
            switch( value )
            {
                case "btc":
                    return CurrencyType.Btc;
                case "eth":
                    return CurrencyType.Eth;
                case "usd":
                    return CurrencyType.Usd;
            }
            return null;
        }
    }
}
