// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IcoCommon.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class EmailModel
    {
        /// <summary>
        /// Initializes a new instance of the EmailModel class.
        /// </summary>
        public EmailModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmailModel class.
        /// </summary>
        public EmailModel(System.DateTime sentUtc, string campaignId = default(string), string templateId = default(string), string to = default(string), string subject = default(string), string body = default(string), IDictionary<string, byte[]> attachments = default(IDictionary<string, byte[]>))
        {
            CampaignId = campaignId;
            TemplateId = templateId;
            To = to;
            Subject = subject;
            Body = body;
            Attachments = attachments;
            SentUtc = sentUtc;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "campaignId")]
        public string CampaignId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "templateId")]
        public string TemplateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "to")]
        public string To { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subject")]
        public string Subject { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "body")]
        public string Body { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attachments")]
        public IDictionary<string, byte[]> Attachments { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "sentUtc")]
        public System.DateTime SentUtc { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
