// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IcoCommon.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EmailModel
    {
        /// <summary>
        /// Initializes a new instance of the EmailModel class.
        /// </summary>
        public EmailModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmailModel class.
        /// </summary>
        public EmailModel(string emailTo = default(string), string campaignId = default(string), string templateId = default(string), object paramsProperty = default(object))
        {
            EmailTo = emailTo;
            CampaignId = campaignId;
            TemplateId = templateId;
            ParamsProperty = paramsProperty;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EmailTo")]
        public string EmailTo { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CampaignId")]
        public string CampaignId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TemplateId")]
        public string TemplateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Params")]
        public object ParamsProperty { get; set; }

    }
}
