// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IcoCommon.Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class EmailDataModel
    {
        /// <summary>
        /// Initializes a new instance of the EmailDataModel class.
        /// </summary>
        public EmailDataModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmailDataModel class.
        /// </summary>
        public EmailDataModel(string campaignId = default(string), string templateId = default(string), string to = default(string), string subject = default(string), object data = default(object), IDictionary<string, byte[]> attachments = default(IDictionary<string, byte[]>))
        {
            CampaignId = campaignId;
            TemplateId = templateId;
            To = to;
            Subject = subject;
            Data = data;
            Attachments = attachments;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "campaignId")]
        public string CampaignId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "templateId")]
        public string TemplateId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "to")]
        public string To { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "subject")]
        public string Subject { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "data")]
        public object Data { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "attachments")]
        public IDictionary<string, byte[]> Attachments { get; set; }

    }
}
