// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IcoCommon.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class EmailTemplateAddOrUpdateRequest
    {
        /// <summary>
        /// Initializes a new instance of the EmailTemplateAddOrUpdateRequest
        /// class.
        /// </summary>
        public EmailTemplateAddOrUpdateRequest()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the EmailTemplateAddOrUpdateRequest
        /// class.
        /// </summary>
        public EmailTemplateAddOrUpdateRequest(EmailTemplateModel emailTemplate = default(EmailTemplateModel), string username = default(string))
        {
            EmailTemplate = emailTemplate;
            Username = username;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "emailTemplate")]
        public EmailTemplateModel EmailTemplate { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "username")]
        public string Username { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
            if (EmailTemplate != null)
            {
                EmailTemplate.Validate();
            }
        }
    }
}
