// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Lykke.Service.IcoCommon.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PayInAddressModel
    {
        /// <summary>
        /// Initializes a new instance of the PayInAddressModel class.
        /// </summary>
        public PayInAddressModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PayInAddressModel class.
        /// </summary>
        /// <param name="currency">Possible values include: 'btc', 'eth',
        /// 'usd'</param>
        public PayInAddressModel(CurrencyType currency, string address = default(string), string campaignId = default(string), string email = default(string))
        {
            Address = address;
            Currency = currency;
            CampaignId = campaignId;
            Email = email;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'btc', 'eth', 'usd'
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public CurrencyType Currency { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "campaignId")]
        public string CampaignId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// Validate the object.
        /// </summary>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown if validation fails
        /// </exception>
        public virtual void Validate()
        {
        }
    }
}
